sd download protections

diff --git a/xilmake b/xilmake
--- a/xilmake
+++ b/xilmake
@@ -504,56 +504,69 @@ if [[ ! -z $SD_CARD ]]; then
 	echo "Downloading boot files to SD card "$SD_CARD
 	echo "------------------------------------------"
 
-	# SD card partition mount locations
-	BOOT_DIR=/mnt/BOOT
-	ROOTFS_DIR=/mnt/rootfs
+	if ls $SD_CARD"1" 1> /dev/null 2>&1; then
 
-	# unmount and remove all partitions
-	partitions=($SD_CARD?)
-	if [[ "$partitions" != $SD_CARD\? ]]; then
-		for ((i=${#partitions[@]}-1; i>=0; i--)); do
-			sudo umount "${partitions[$i]}"
-			sudo parted $SD_CARD rm "${partitions[$i]: -1}"
-		done
+		if ! blkid $SD_CARD"1" | grep -q vfat ; then
+			read -p "SD card partition 1 (boot partition) is not FAT. Are you sure you want to continue? (y / n)" yn
+		else
+			yn=y
+		fi
+
+		if [[ $yn == "y"* ]] ; then
+			# SD card partition mount locations
+			BOOT_DIR=/mnt/BOOT
+			ROOTFS_DIR=/mnt/rootfs
+
+			# unmount and remove all partitions
+			partitions=($SD_CARD?)
+			if [[ "$partitions" != $SD_CARD\? ]]; then
+				for ((i=${#partitions[@]}-1; i>=0; i--)); do
+					sudo umount "${partitions[$i]}"
+					sudo parted $SD_CARD rm "${partitions[$i]: -1}"
+				done
+			fi
+
+			# create partition table
+			sudo parted $SD_CARD -s mklabel msdos
+
+			# create boot partition
+			sudo parted $SD_CARD mkpart primary fat32 4MiB 516MiB
+			# create rootfs partition
+			sudo parted $SD_CARD mkpart primary ext4 516MiB 100%
+
+			# format boot as fat32
+			sudo mkfs.fat -F32 -n BOOT $SD_CARD"1"
+			# format rootfs as ext4
+			sudo mkfs.ext4 -F -L rootfs $SD_CARD"2"
+
+			# mount boot partition
+			sudo mkdir -p $BOOT_DIR
+			sudo mount $SD_CARD"1" $BOOT_DIR
+
+			# mount rootfs partition
+			sudo mkdir -p $ROOTFS_DIR
+			sudo mount $SD_CARD"2" $ROOTFS_DIR
+
+			# copy FSBL, u-boot, bitstream into boot partition
+			sudo cp -f $LINUX_PROJECT_DIR"/images/linux/BOOT.BIN" $BOOT_DIR
+			# add additional u-boot environment variables into boot partition
+			echo 'uenvcmd=if test -n ${ipaddr}; then tftpboot ${clobstart} system.bit; fpga loadb 0 ${clobstart} ${filesize}; run update_boot; run update_kernel; else echo "No ethernet connection, skipping TFTP update..."; fi' | sudo tee $BOOT_DIR"/uEnv.txt" > /dev/null
+
+			# copy kernel into boot partition
+			sudo cp -f $LINUX_PROJECT_DIR"/images/linux/image.ub" $BOOT_DIR
+
+			# decompress linux into rootfs partition
+			sudo tar -xzf $LINUX_PROJECT_DIR"/images/linux/rootfs.tar.gz" -C $ROOTFS_DIR
+
+			# unmount partitions
+			sudo umount $SD_CARD"2"
+			sudo umount $SD_CARD"1"
+			sudo rm -rf $BOOT_DIR
+			sudo rm -rf $ROOTFS_DIR
+		fi
+	else
+		echo "SD card specified was not found. Not downloading..."
 	fi
-
-	# create partition table
-	sudo parted $SD_CARD -s mklabel msdos
-
-	# create boot partition
-	sudo parted $SD_CARD mkpart primary fat32 4MiB 516MiB
-	# create rootfs partition
-	sudo parted $SD_CARD mkpart primary ext4 516MiB 100%
-
-	# format boot as fat32
-	sudo mkfs.fat -F32 -n BOOT $SD_CARD"1"
-	# format rootfs as ext4
-	sudo mkfs.ext4 -F -L rootfs $SD_CARD"2"
-
-	# mount boot partition
-	sudo mkdir -p $BOOT_DIR
-	sudo mount $SD_CARD"1" $BOOT_DIR
-
-	# mount rootfs partition
-	sudo mkdir -p $ROOTFS_DIR
-	sudo mount $SD_CARD"2" $ROOTFS_DIR
-
-	# copy FSBL, u-boot, bitstream into boot partition
-	sudo cp -f $LINUX_PROJECT_DIR"/images/linux/BOOT.BIN" $BOOT_DIR
-	# add additional u-boot environment variables into boot partition
-	echo 'uenvcmd=if test -n ${ipaddr}; then tftpboot ${clobstart} system.bit; fpga loadb 0 ${clobstart} ${filesize}; run update_boot; run update_kernel; else echo "No ethernet connection, skipping TFTP update..."; fi' | sudo tee $BOOT_DIR"/uEnv.txt"
-
-	# copy kernel into boot partition
-	sudo cp -f $LINUX_PROJECT_DIR"/images/linux/image.ub" $BOOT_DIR
-
-	# decompress linux into rootfs partition
-	sudo tar -xzf $LINUX_PROJECT_DIR"/images/linux/rootfs.tar.gz" -C $ROOTFS_DIR
-
-	# unmount partitions
-	sudo umount $SD_CARD"2"
-	sudo umount $SD_CARD"1"
-	sudo rm -rf $BOOT_DIR
-	sudo rm -rf $ROOTFS_DIR
 fi
 
 END_TIME="$(date -u +%s)"
